#!/bin/sh

. /etc/update-motd.d/quiet
. /etc/update-motd.d/colors

------------------------------------------------------------------------------
Welcome to the Proxmox Virtual Environment by 𝐶𝛳𝐷𝐼𝛱𝐺'𝛱𝛴𝑃𝛥𝐿𝛴. Please use your web browser to 
configure this server - connect to:
https://ip:8006/
------------------------------------------------------------------------------
